description = "âš¡ Run tests locally and analyze the summary report."
prompt = """

## Your Resources:

**IMPORTANT**: Always analyze the list of agents and skills, intelligently activate the skills and its scripts that are needed for the task during the process. Execute this command to check

```bash
gk catalog skills

gk catalog agents
```


## Your Approach:
- Spawn the `tester` agent to run tests locally and analyze the summary report.
- **IMPORTANT**: Always use `gk agent search` to find optimal combination agent-skills before `spawn-agent` 
```bash
gk agent search "{task}"
```
* Spawn `tester` agent example:
```bash
gk agent spawn --prompt "[Your task description]" --agent "tester" --skills "problem-solving" --context "@referenced_document.md"
```
    
**IMPORTANT**: **Do not** start implementing.
**IMPORTANT:** Analyze the skills catalog and activate the skills that are needed for the task during the process.

"""